"""initial migration

Revision ID: b2342c79a9f2
Revises: 
Create Date: 2026-06-20 11:02:57.976665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2342c79a9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservationservices',
    sa.Column('ReservationServiceID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.Column('TotalPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('OrderDateTime', sa.DateTime(), nullable=True),
    sa.Column('ReservationID', sa.Integer(), nullable=True),
    sa.Column('ServiceID', sa.Integer(), nullable=True),
    sa.Column('EmployeeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employees.EmployeeID'], ),
    sa.ForeignKeyConstraint(['ReservationID'], ['reservations.ReservationID'], ),
    sa.ForeignKeyConstraint(['ServiceID'], ['services.ServiceID'], ),
    sa.PrimaryKeyConstraint('ReservationServiceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservationservices')
    # ### end Alembic commands ###
