"""fix reservation service column

Revision ID: c259d45c0d91
Revises: b2342c79a9f2
Create Date: 2026-06-28 02:54:17.490664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c259d45c0d91'
down_revision = 'b2342c79a9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservationservices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ServiceId', sa.Integer(), nullable=False))
        batch_op.drop_column('ReservationServiceID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservationservices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ReservationServiceID', sa.INTEGER(), nullable=False))
        batch_op.drop_column('ServiceId')

    # ### end Alembic commands ###
